{% set name = "jsonlines" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2579cb488d96f815b0eb81629e3e6b0332da0962a18fa3532958f7ba14a5c37f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - attrs >=19.2.0
    - typing_extensions

test:
  imports:
    - jsonlines
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/wbolster/jsonlines
  license_file: LICENSE.rst
  license: BSD-3-Clause
  license_family: BSD
  summary: Library with helpers for the jsonlines file format
  dev_url: https://github.com/wbolster/jsonlines
  doc_url: https://jsonlines.readthedocs.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - asford
