{% set name = "jsonlines" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43b8d5588a9d4862c8a4a49580e38e20ec595aee7ad6fe469b10fb83fbefde88

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - jsonlines
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/wbolster/jsonlines
  license_file: LICENSE.rst
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Library with helpers for the jsonlines file format'
  dev_url: https://github.com/wbolster/jsonlines
  doc_url: https://jsonlines.readthedocs.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - BastianZim
