{% set name = "jsonlines" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 72c8ca6c056906d6acb058dd5fdd5e072a58b9c6753ce0c9ec6f2b0a1853eba4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - jsonlines
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/wbolster/jsonlines
  license_file: LICENSE.rst
  license: BSD-3-Clause
  license_family: BSD
  summary: Library with helpers for the jsonlines file format
  dev_url: https://github.com/wbolster/jsonlines
  doc_url: https://jsonlines.readthedocs.org/

extra:
  recipe-maintainers:
    - pmlandwehr
